import * as yup from "yup";
import { MESSAGES } from "../../main/constants/messages";
import { REGEX } from "../../main/constants/regex";

export const loginValidationSchema = yup.object().shape({
  email: yup
    .string()
    .email(MESSAGES.VALIDATION.EMAIL_FORMAT)
    .matches(REGEX.EMAIL_DOMAIN, MESSAGES.VALIDATION.EMAIL_DOMAIN)
    .required(MESSAGES.VALIDATION.EMAIL_REQUIRED),

  password: yup
    .string()
    .required(MESSAGES.VALIDATION.PASSWORD_REQUIRED)
    .min(8, MESSAGES.VALIDATION.PASSWORD_MIN_LENGTH)
    .matches(REGEX.PASSWORD.LOWERCASE, MESSAGES.VALIDATION.PASSWORD_LOWERCASE)
    .matches(REGEX.PASSWORD.UPPERCASE, MESSAGES.VALIDATION.PASSWORD_UPPERCASE)
    .matches(REGEX.PASSWORD.DIGITS, MESSAGES.VALIDATION.PASSWORD_DIGITS)
    .matches(
      REGEX.PASSWORD.SPECIAL_CHARACTERS,
      MESSAGES.VALIDATION.PASSWORD_SPECIAL_CHARACTERS,
    ),
});

export const signupValidationSchema = yup.object().shape({
  firstName: yup
    .string()
    .required(MESSAGES.VALIDATION.FIRST_NAME_REQUIRED)
    .min(2, MESSAGES.VALIDATION.FIRST_NAME_MIN_LENGTH),

  lastName: yup
    .string()
    .required(MESSAGES.VALIDATION.LAST_NAME_REQUIRED)
    .min(2, MESSAGES.VALIDATION.LAST_NAME_MIN_LENGTH),

  email: yup
    .string()
    .required(MESSAGES.VALIDATION.EMAIL_REQUIRED)
    .matches(REGEX.EMAIL_DOMAIN, MESSAGES.VALIDATION.EMAIL_DOMAIN),

  password: yup
    .string()
    .required(MESSAGES.VALIDATION.PASSWORD_REQUIRED)
    .matches(REGEX.PASSWORD.LOWERCASE, MESSAGES.VALIDATION.PASSWORD_LOWERCASE)
    .matches(REGEX.PASSWORD.UPPERCASE, MESSAGES.VALIDATION.PASSWORD_UPPERCASE)
    .matches(REGEX.PASSWORD.DIGITS, MESSAGES.VALIDATION.PASSWORD_DIGITS)
    .matches(
      REGEX.PASSWORD.SPECIAL_CHARACTERS,
      MESSAGES.VALIDATION.PASSWORD_SPECIAL_CHARACTERS,
    ),

  phoneNumber: yup
    .string()
    .required(MESSAGES.VALIDATION.PHONE_NUMBER_REQUIRED)
    .matches(REGEX.PHONE_NUMBER, MESSAGES.VALIDATION.PHONE_NUMBER_FORMAT),
});
